### ISSUE TITLE
Attend Current State FTA Review - Oct 24

### ISSUE THREAD

**Issue by JLWade** [bcgov/rec-resources#22]
Attend Current State FTA Review with program area experts to learn about the legacy tool. 

#### Acceptance Criteria:
- [x] all team members have attended this meeting and have an overview of the tool
  - [x] @marcellmueller 
  - [x] @JLWade 
  - [x] @FM-SM 
  - [x] Winnie
  - [x] @jaimiebutton 
  - [x] Alberto

**Definition of Ready**
TBD

**Definition of Done** 
TBD
#### Notes:
- 
-

**Comment by FM-SM** [comment]
Meeting attended by all team  members
