### ISSUE TITLE
Review current state FTA/RST data

### ISSUE THREAD

**Issue by JLWade** [bcgov/rec-resources#23]
Overview of current state data model and architecture of the FTA tool. We will need to eventually use/migrate/take ownership of this data so this ticket is to get a better understanding of the data.

#### Acceptance Criteria:
- [x] current FTA/RST data models have been reviewed
  - [x] associated documentation is stored in confluence or our teams channel
- [x] devs have basic understanding of data and data structure 

#### Development Checklist:

- [x] Connect with NRIDS architects (@JLWade  can assist with this)
- [x] Access to Jasper reports to see sample data
- [x] Utilize data model reports for reference (@jaimiebutton  might have these saved)
- [x] @jaimiebutton has a great mural board to see how data is shown on front end that would be worth taking a look at

#### Dependencies

- Work with the architects to get access to the data
- Make sure everyone involved has access to it (confluence)
- Get access to Jaspersoft

#### Relates to:
#57 

**Definition of Ready**
TBD

**Definition of Done** 
TBD

**Notes:
Links to it will be provided (in case the access becomes an issue, developers can still go over it)

**Comment by FM-SM** [comment]
Moving to Blocked as @JLWade gets access to Jasper
