### ISSUE TITLE
Hold a team session to align on ticket estimation

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/rec-resources#45]
How will our team estimate tickets? What constitutes as 1 vs an 8? When should we estimate based on effort vs time?

Acceptance Criteria:
- [ ] Meet as a group
- [ ] Discuss how we'll estimate
- [ ] Document our estimation decision for historical context

Note: 
- This work connects to our Team Agreements (#30 )
- Diana has a great exercise using fruits we can borrow

**Comment by FM-SM** [comment]
I've assigned this ticket to myself so I can host this alignment session

**Comment by JLWade** [comment]
@FM-SM - any update on this piece? Will we need this for refinement and/or sprint planning next week or shall we try a different approach/no estimates for next sprint? What is your recommendation?

**Comment by FM-SM** [comment]
@JLWade I have scheduled the estimation workshop for Tuesday.

**Comment by FM-SM** [comment]
Closing this ticket as the session happened as planned
